[package]
name = "git-server-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.10.2"
actix-cors = "0.6.4"
base64 = "0.22.1"
bcrypt = "0.15"
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono", "migrate", "uuid"]}
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.7.0", features = ["v4", "serde"] }
jsonwebtoken = "9.2"
rand = "0.9.1"
actix-rt = "2.9"
sha2 = "0.10"
reqwest = { version = "0.12", features = ["json"] }
hostname = "0.4"

[[bin]]
name = "git-server-backend"
path = "src/main.rs"
